### ISSUE TITLE
Not working for me on paper 1.16.5

### ISSUE THREAD

**Issue by FrogWithoutLegs** [DerFrZocker/Ore-Control#2]
The plugin is there, I can use the GUI and edit all the values, but it doesnt actually change anything. I've tried reloading, restarting the server, loading new chunks, but it doesnt actually change the ores.

**Comment by Sitmobedaf** [comment]
Hello, can you create release for Spigot 1.17?

**Comment by DerFrZocker** [comment]
Are there any error messages in the console, during server start?

**Comment by DerFrZocker** [comment]
With v2 1.16.5 is no longer supported.
