### ISSUE TITLE
Ore Control  2021.06.29 with Datapack  caves-amp-cliffs-expansion not working

### ISSUE THREAD

**Issue by l3unnyAnoF4** [DerFrZocker/Ore-Control#6]
I don't see any changes Overworld

1.17.1
https://www.planetminecraft.com/data-pack/caves-amp-cliffs-expansion-pack-20w20a-compatible/
c-c-expansionpack-1-5-2-1.zip

**Comment by DerFrZocker** [comment]
Custom Biomes as well as the caves and cliffs data pack is not supported
